version: "3.8"
services:
  e2e:
    image: mpre-pw
    build: .
    platform: linux/amd64
    extra_hosts:
    - "127.0.0.1:127.0.0.1"
    ports:
      - "9323:9323"
    container_name: automation       
    environment:   
      CI: 'true'
      CIRCLE_BRANCH: ${CIRCLE_BRANCH}  
      CIRCLE_BUILD_URL: ${CIRCLE_BUILD_URL:-}
      CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM:-}
      CIRCLE_JOB: ${CIRCLE_JOB:-}
      EMAIL_LIST: ${EMAIL_LIST:-}   
      EMAIL_TOKEN: ${EMAIL_TOKEN:-}   
      EMAIL_DOMAIN: ${EMAIL_DOMAIN:-}   
      EMAIL_REPORTER: ${EMAIL_REPORTER:-}                                         
      TEST_SCRIPT: npm run test                                              
      REPORT: playwright                                                           
      REPORT_DIR: './'       
    privileged: true
    command:
       bash -c './execute_test.sh'   
    volumes:
     - $PWD/artifacts/playwright-report:/playwright-report      
    tty: true
    stdin_open: true